language: php

php:
  - 5.6
  - 7.0

before_install:
  - composer self-update
  - composer install

before_script:
  - bin/console setup:mysql-database
  - bin/console setup:sqlite-database

script:
  - vendor/bin/phpunit